### PR TITLE
Mcs 2394 gamepad tutorial

### PR DESCRIPTION
**Pull request by anchi1216**
@iamblue @dariachen @appleboy 

Dear all, 
please take a look to see if the tutorial is okay. Thanks.

### CODE REVIEW

**Comment by iamblue** [comment]
gooood!!!

**Comment by yutin1987** [comment]
:tada:

**Comment by dariachen** [comment]
1. 針對 “data_channel_format.md” 中提到 “The keyboard default pre-defined value is as following:” 要不要直接跟使用者說 "You can use pre-defined hotkeys on keyboard to control this data channel". 不然怕會跟送出的 value 搞混?
2. "7688_gamepad_tutorial.md" typos
   2.1. "gamepag" should be "gamepad" 
   2.2. "navigator bar" should be "navigation bar"
   2.3. "on the right upper corner" should be "in the upper-right corner"

**Comment by anchi1216** [comment]
@dariachen 謝謝! 已更改~~

**Comment by dariachen** [comment]
Looks good!

**Pull request merged**
